# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2sT8tG4wuzkV7rRDq9IiVr_I7e2H9RJ
"""

from __future__ import annotations
import os
import json
import math
from dataclasses import dataclass
from typing import Tuple, Dict, Any, List


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error, mean_squared_error


# statsmodels for ARIMA baseline
from statsmodels.tsa.arima.model import ARIMA


# NeuralProphet and Optuna
from neuralprophet import NeuralProphet
import optuna


# -----------------------------
# Utilities and Data Generation
# -----------------------------


np.random.seed(42)


@dataclass
class DatasetConfig:
start_date: str = "2018-01-01"
periods: int = 1500 # ~4+ years of daily data
freq: str = "D"




def generate_synthetic_series(cfg: DatasetConfig) -> pd.DataFrame:
"""Generate a synthetic daily time series with multiple seasonalities (yearly, weekly, daily) and three regressors.


Returns a dataframe with columns: ds (datetime), y (target), reg1, reg2, reg3
"""
rng = pd.date_range(start=cfg.start_date, periods=cfg.periods, freq=cfg.freq)
t = np.arange(len(rng))


# Base trend (slight upward linear trend)
trend = 0.0008 * t


# Yearly seasonality (approx using a sine with period 365)
yearly = 10 * np.sin(2 * np.pi * t / 365.25)


# Weekly seasonality (7-day pattern): higher values on weekends
weekly = 3 * np.sin(2 * np.pi * t / 7)


# Daily-like micro variation (short-term noise patterns)
short = 1.5 * np.sin(2 * np.pi * t / 3.5)


# External regressors simulation
# reg1: a promotion flag - sparse spikes
reg1 = (np.random.rand(len(rng)) < 0.04).astype(float)


# reg2: weather index - continuous [-1, 1] with some autocorrelation
metrics = model.fit(train_df, va